---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: submariner
      namespace: submariner-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-0.12'
