---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'alpha'
    target:
      kind: Subscription
      name: dbaas-operator
resources:
  - ../../base
