apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true


resources:
- grafana-ds.yaml
- cluster-monitor-view-rb.yaml
- grafana-auth-secret.yaml
- ../../base/operator
- ../../base/instance

patches:
- patch: |-
    - op: add
      path: /spec/deployment
      value:
        env:
        - name: GRAFANA_TOKEN
          valueFrom:
            secretKeyRef:
              name: grafana-auth-secret
              key: token
  target:
    kind: Grafana
    name: grafana
