kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: rhacs-operator


patches:
- patch: |-
    - op: replace
      path: /spec/channel
      value: 'latest'
  target:
    kind: Subscription
    name: rhacs-operator
resources:
- ../../base
