name: Validate Manifests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint-kustomize:
    runs-on: ubuntu-latest
    env:
      KUSTOMIZE_VERSION: 5.0.0
      KUSTOMIZE_URL: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
      BIN_PATH: /usr/bin
    steps:
      - name: Install Kustomize
        run: |
          sudo curl --location --no-buffer "${KUSTOMIZE_URL}" | tar -xvf - -C ${BIN_PATH}/
          sudo chmod +x ${BIN_PATH}/kustomize
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Validate Manifests
        run: |
          [ -d ./bootstrap/base ] && touch bootstrap/base/sealed-secrets-secret.yaml
          ./scripts/validate_manifests.sh

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github

  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.8.0
          severity: warning
